#include "features/HoleFeature.h"

#include "features/BodyOps.h"
#include "geom/OcctUtil.h"
#include "topo/Resolver.h"

#include <BRepBuilderAPI_MakeFace.hxx>
#include <BRepBuilderAPI_MakePolygon.hxx>
#include <BRepPrimAPI_MakeRevol.hxx>
#include <BRepTools_WireExplorer.hxx>
#include <TopExp.hxx>
#include <TopoDS.hxx>

#include <algorithm>
#include <cmath>

namespace cad {

namespace {

const char *holeTypeName(HoleType t) {
    switch(t) {
    case HoleType::Simple: return "simple";
    case HoleType::Counterbore: return "counterbore";
    case HoleType::Countersink: return "countersink";
    }
    return "simple";
}

HoleType holeTypeFromName(const std::string &s) {
    if(s == "counterbore") return HoleType::Counterbore;
    if(s == "countersink") return HoleType::Countersink;
    return HoleType::Simple;
}

struct ProfilePt {
    double r, z;
    const char *role; // name of the face generated by the segment starting here
};

// Revolves the (r, z) half-profile around the axis through `at` along `up`
// (z > 0 is above the placement face) and names the faces by segment role.
bool makeHoleTool(const std::vector<ProfilePt> &pts, const gp_Pnt &at, const gp_Dir &up, const gp_Dir &radial,
                  const std::string &prefix, NamedShape &out) {
    BRepBuilderAPI_MakePolygon poly;
    for(const auto &p : pts) poly.Add(gp_Pnt(at.XYZ() + radial.XYZ() * p.r + up.XYZ() * p.z));
    poly.Close();
    if(!poly.IsDone()) return false;
    const TopoDS_Wire wire = poly.Wire();
    BRepBuilderAPI_MakeFace mf(wire, Standard_True);
    if(!mf.IsDone()) return false;
    BRepPrimAPI_MakeRevol revol(mf.Face(), gp_Ax1(at, up), 2.0 * M_PI);
    revol.Build();
    if(!revol.IsDone()) return false;

    TopTools_IndexedMapOfShape fmap;
    TopExp::MapShapes(revol.Shape(), TopAbs_FACE, fmap);
    std::vector<FaceLabel> labels(size_t(fmap.Extent()));
    size_t k = 0;
    for(BRepTools_WireExplorer ex(wire); ex.More() && k < pts.size(); ex.Next(), ++k) {
        for(TopTools_ListOfShape::Iterator it(revol.Generated(ex.Current())); it.More(); it.Next()) {
            const int j = fmap.FindIndex(it.Value());
            if(j > 0) labels[j - 1].name = prefix + "/" + pts[k].role;
        }
    }
    for(auto &l : labels)
        if(l.name.empty()) l.name = prefix + "/other";
    out = NamedShape(revol.Shape(), std::move(labels));
    return true;
}

} // namespace

std::vector<ParamDef> HoleFeature::params() const {
    std::vector<ParamDef> out;
    auto add = [&](const ParamSlot &s, ValueKind k, const char *label) {
        if(!s.empty()) out.push_back({s.name, s.expr, k, id, name + " " + label});
    };
    add(diameter, ValueKind::Length, "Diameter");
    add(depth, ValueKind::Length, "Depth");
    add(cboreDiameter, ValueKind::Length, "Counterbore Diameter");
    add(cboreDepth, ValueKind::Length, "Counterbore Depth");
    add(csinkDiameter, ValueKind::Length, "Countersink Diameter");
    add(csinkAngle, ValueKind::Angle, "Countersink Angle");
    add(tipAngle, ValueKind::Angle, "Drill Point Angle");
    return out;
}

json HoleFeature::dataToJson() const {
    json pts = json::array();
    for(const auto &p : points) pts.push_back(cad::toJson(p));
    json j{{"points", pts},
           {"sketch", sketch},
           {"sketchPoints", sketchPoints},
           {"holeType", holeTypeName(holeType)},
           {"extent", extent == ExtentType::ThroughAll ? "throughAll" : "distance"},
           {"diameter", diameter.toJson()},
           {"depth", depth.toJson()},
           {"cboreDiameter", cboreDiameter.toJson()},
           {"cboreDepth", cboreDepth.toJson()},
           {"csinkDiameter", csinkDiameter.toJson()},
           {"csinkAngle", csinkAngle.toJson()},
           {"tipAngle", tipAngle.toJson()},
           {"flatTip", flatTip}};
    if(!face.empty()) j["face"] = face.toJson();
    return j;
}

void HoleFeature::dataFromJson(const json &j) {
    face = TopoRef::fromJson(j.value("face", json()));
    points.clear();
    for(const auto &p : j.value("points", json::array())) points.push_back(vec2FromJson(p));
    sketch = jget<int>(j, "sketch", kNoFeature);
    sketchPoints = jget<std::vector<int>>(j, "sketchPoints", {});
    holeType = holeTypeFromName(jget<std::string>(j, "holeType", ""));
    extent = jget<std::string>(j, "extent", "") == "throughAll" ? ExtentType::ThroughAll : ExtentType::Distance;
    diameter = ParamSlot::fromJson(j.value("diameter", json()));
    depth = ParamSlot::fromJson(j.value("depth", json()));
    cboreDiameter = ParamSlot::fromJson(j.value("cboreDiameter", json()));
    cboreDepth = ParamSlot::fromJson(j.value("cboreDepth", json()));
    csinkDiameter = ParamSlot::fromJson(j.value("csinkDiameter", json()));
    csinkAngle = ParamSlot::fromJson(j.value("csinkAngle", json()));
    tipAngle = ParamSlot::fromJson(j.value("tipAngle", json()));
    flatTip = jget<bool>(j, "flatTip", false);
}

std::vector<FeatureId> HoleFeature::dependencies() const {
    if(sketch != kNoFeature) return {sketch};
    return {};
}

FeatureResult HoleFeature::compute(const StatePtr &input, const ComputeContext &ctx) const {
    return guardedCompute(input, [&]() -> FeatureResult {
        Status st;

        // Placement: centres, the outward direction, and candidate bodies.
        std::vector<gp_Pnt> centres;
        gp_Dir up(0, 0, 1), radial(1, 0, 0);
        std::vector<BodyId> targets;
        if(!face.empty()) {
            ResolvedRef r = resolveRef(*input, face);
            st.merge(r.status);
            if(!r.ok) return {input, st};
            gp_Pln pln;
            if(!planeOfFace(TopoDS::Face(r.shape), pln)) return {input, Status::error("holes need a planar face")};
            const gp_Ax3 frame = frameForPlane(pln);
            up = frame.Direction();
            radial = frame.XDirection();
            for(const auto &p : points)
                centres.push_back(gp_Pnt(frame.Location().XYZ() + frame.XDirection().XYZ() * p.x +
                                         frame.YDirection().XYZ() * p.y));
            targets.push_back(r.body->id);
        } else if(sketch != kNoFeature) {
            auto it = input->sketches.find(sketch);
            if(it == input->sketches.end()) return {input, Status::error("the hole's sketch is missing")};
            const SketchResult &sk = *it->second;
            up = sk.frame.Direction();
            radial = sk.frame.XDirection();
            for(int pid : sketchPoints) {
                const SkEntity *e = sk.sketch.find(pid);
                if(!e || e->type != SkType::Point) {
                    st.merge(Status::warning("a hole point no longer exists"));
                    continue;
                }
                centres.push_back(sk.toWorld({e->x, e->y}));
            }
        }
        if(centres.empty()) return {input, Status::error("place the hole on a face or at sketch points")};

        double dia = 0.0, dep = 0.0, tip = 0.0;
        if(!ctx.value(diameter, dia, st)) return {input, st};
        if(dia <= 0.0) return {input, Status::error("the hole diameter must be positive")};
        const double big = 2.0 * input->modelSize() + 10.0;
        if(extent == ExtentType::ThroughAll) {
            dep = big;
        } else {
            if(!ctx.value(depth, dep, st)) return {input, st};
            if(dep <= 0.0) return {input, Status::error("the hole depth must be positive")};
        }
        const bool flat = flatTip || extent == ExtentType::ThroughAll;
        if(!flat) {
            if(!ctx.value(tipAngle, tip, st, ValueKind::Angle)) return {input, st};
            if(tip <= 0.0 || tip >= M_PI) return {input, Status::error("the drill point angle must be between 0 and 180")};
        }

        // Half profile (r, z): z = 0 on the face, negative into the material.
        const double r = 0.5 * dia;
        const double above = std::max(0.5, 0.2 * dia);
        std::vector<ProfilePt> pts;
        switch(holeType) {
        case HoleType::Simple:
            pts = {{0, above, "top"}, {r, above, "bore"}};
            break;
        case HoleType::Counterbore: {
            double cd = 0.0, ch = 0.0;
            if(!ctx.value(cboreDiameter, cd, st) || !ctx.value(cboreDepth, ch, st)) return {input, st};
            if(cd <= dia) return {input, Status::error("the counterbore must be wider than the hole")};
            if(ch <= 0.0 || ch >= dep) return {input, Status::error("the counterbore depth must be less than the hole depth")};
            pts = {{0, above, "top"}, {0.5 * cd, above, "cbore"}, {0.5 * cd, -ch, "cboreFloor"}, {r, -ch, "bore"}};
            break;
        }
        case HoleType::Countersink: {
            double sd = 0.0, sa = 0.0;
            if(!ctx.value(csinkDiameter, sd, st) || !ctx.value(csinkAngle, sa, st, ValueKind::Angle)) return {input, st};
            if(sd <= dia) return {input, Status::error("the countersink must be wider than the hole")};
            if(sa <= 0.0 || sa >= M_PI) return {input, Status::error("the countersink angle must be between 0 and 180")};
            const double R = 0.5 * sd;
            const double hc = (R - r) / std::tan(0.5 * sa);
            if(hc >= dep) return {input, Status::error("the countersink is deeper than the hole")};
            pts = {{0, above, "top"}, {R, above, "csinkWall"}, {R, 0, "csink"}, {r, -hc, "bore"}};
            break;
        }
        }
        if(flat) {
            pts.push_back({r, -dep, "floor"});
            pts.push_back({0, -dep, "axis"});
        } else {
            pts.push_back({r, -dep, "tip"});
            pts.push_back({0, -dep - r / std::tan(0.5 * tip), "axis"});
        }

        std::vector<NamedShape> tools(centres.size());
        for(size_t k = 0; k < centres.size(); ++k) {
            const std::string prefix = "f" + std::to_string(id) + "/h" + std::to_string(k + 1);
            if(!makeHoleTool(pts, centres[k], up, radial, prefix, tools[k]))
                return {input, Status::error("could not build the hole shape")};
        }
        std::vector<const NamedShape *> toolPtrs;
        for(const auto &t : tools) toolPtrs.push_back(&t);

        if(targets.empty()) {
            const TopoDS_Shape all = [&] {
                std::vector<TopoDS_Shape> v;
                for(const auto &t : tools) v.push_back(t.shape());
                return makeCompound(v);
            }();
            targets = bodiesInteracting(*input, all, false);
        }
        if(targets.empty()) return {input, Status::error("the hole does not touch any body")};

        auto out = std::make_shared<ModelState>(*input);
        const std::string prefix = "f" + std::to_string(id);
        for(const auto &b : targets) {
            BooleanResult br = runBoolean(BoolOp::Cut, {&input->body(b)->shape}, toolPtrs, prefix);
            if(!br.ok) return {input, Status::error(br.error)};
            if(!validateResult(br.shape, prefix, st)) return {input, st};
            replaceBody(*out, b, br.shape);
        }
        return {out, st};
    });
}

} // namespace cad
